#!/bin/sh
cat /README.Docker
echo "Start Xvfb"
/opt/bin/start-xvfb.sh &
sleep 2
cd /testar/bin
./testar sse=distributed_labrecruits ShowVisualSettingsDialogOnStartup=false ShowSettingsAfterTest=false VisualizeSelectedAction=false FlashFeedback=false Mode=Generate LabRecruitsGraphics=false MaxTime=300
#sh -c "while true; do sleep 1; done"